"""initial migrations

Revision ID: bc3a00c79d98
Revises: 
Create Date: 2020-03-31 19:20:34.295908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc3a00c79d98'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=64), nullable=True),
    sa.Column('cover', sa.String(length=255), nullable=True),
    sa.Column('year', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('douban_score', sa.String(length=32), nullable=True),
    sa.Column('duration', sa.String(length=64), nullable=True),
    sa.Column('director', sa.String(length=128), nullable=True),
    sa.Column('actors', sa.TEXT(), nullable=True),
    sa.Column('profile', sa.TEXT(), nullable=True),
    sa.Column('prize', sa.TEXT(), nullable=True),
    sa.Column('download_url', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.drop_table('movie')
    # ### end Alembic commands ###
