"""title modify unique false

Revision ID: ff9116aa0e9c
Revises: bc3a00c79d98
Create Date: 2020-03-31 19:40:42.995375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff9116aa0e9c'
down_revision = 'bc3a00c79d98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movie_title', table_name='movie')
    op.create_index(op.f('ix_movie_title'), 'movie', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movie_title'), table_name='movie')
    op.create_index('ix_movie_title', 'movie', ['title'], unique=True)
    # ### end Alembic commands ###
